name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21, 1.22, 1.23]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out

    - name: Build
      run: go build -v ./cmd/server

    - name: Run end-to-end tests
      run: |
        # Start server in background
        ./mock_cors_server &
        SERVER_PID=$!

        # Wait for server to start
        sleep 2

        # Run tests
        go run test.go

        # Clean up
        kill $SERVER_PID || true

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o mock_cors_server-linux-amd64 ./cmd/server
        GOOS=darwin GOARCH=amd64 go build -o mock_cors_server-darwin-amd64 ./cmd/server
        GOOS=darwin GOARCH=arm64 go build -o mock_cors_server-darwin-arm64 ./cmd/server
        GOOS=windows GOARCH=amd64 go build -o mock_cors_server-windows-amd64.exe ./cmd/server

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: mock_cors_server-*
